name: ci

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install
        uses: astral-sh/setup-uv@v6

      - name: setup
        run: uv sync --group dev

      - name: format
        run: uv run ruff format . --check --diff

      - name: lint
        run: uv run ruff check --output-format=github .

      - name: type
        run: uv run pyright

      - name: test
        run: uv run pytest
