#------------------------------------------------------------------------------#
# @note: you may want to remove this action, it only runs if/when the makefile
#        changes to make sure we POSIXy
#------------------------------------------------------------------------------#
name: on-makefile-change

on:
  push:
    branches:
      - master
      - dev
    paths:
      - Makefile
  pull_request:
    branches:
      - master
      - dev
    paths:
      - Makefile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install::pdpmake
        run : |
          git clone https://github.com/rmyorston/pdpmake pdpmake-src
          cd pdpmake-src
          make
          mkdir -p "$HOME/.local/bin"
          mv ./make "$HOME/.local/bin/pdpmake"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          cd ..
          rm -rf pdpmake-src

      - name: make::install
        run : pdpmake install

      - name: make::build
        run : pdpmake build

      # ensures all make targets are aok and run
      - name: make::run:all
        run : |
          printf '%*s\n' 60 "" | tr ' ' '#' ; echo "# TESTING FOLLOWING MAKE TARGETS" ; printf '%*s\n' 60 "" | tr ' ' '#'
          awk --posix '/^[A-Za-z0-9_ -]*:.*##.*$/ {sub(/:.*/,"",$1); print $1}' ./Makefile
          printf '%*s\n' 60 "" | tr ' ' '#' ;
          awk --posix '/^[A-Za-z0-9_ -]*:.*##.*$/ {sub(/:.*/,"",$1); print $1}' ./Makefile | grep --invert-match -E 'watch|bin' | xargs pdpmake

